theme = "monokai_pro_ristretto"


[editor]
color-modes = true
completion-timeout = 5
end-of-line-diagnostics = "hint"
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
line-number = "relative"
text-width = 120
mouse = false
popup-border = "all"
true-color = true
rulers = [120]


[editor.auto-pairs]
'<' = '>'
'[' = ']'
'(' = ')'
'{' = '}'
'"' = '"'
'`' = '`'
"'" = "'"


[editor.auto-save]
focus-lost = true


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"


[editor.file-picker]
hidden = false


[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "error"


[editor.soft-wrap]
enable = true


[editor.statusline]
left = ["mode", "spinner", "spacer", "version-control", "spacer", "diagnostics"]
center = ["file-name", "file-modification-indicator"]
right = ["selections", "position", "file-type", "file-encoding"]
