theme = "gruvbox"

#
# Config
#

[editor]
completion-timeout = 5
cursorline = true
end-of-line-diagnostics = "hint"
gutters = ["diff", "diagnostics", "line-numbers", "spacer", "spacer", "spacer"]
line-number = "relative"
true-color = true
undercurl = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "error"

[editor.soft-wrap]
enable = true

[editor.statusline]
right = ["diagnostics", "spacer", "version-control", "spacer", "file-type"]

#
# Keybinds
#

[keys.normal]
X = ["extend_line_above"]

[keys.select]
X = ["extend_line_above"]
