theme = "gruvbox_dark_hard"

[editor]
bufferline = "always"
color-modes = true
completion-timeout = 5
cursorline = true
end-of-line-diagnostics = "hint"
idle-timeout = 0
gutters = ["spacer", "diagnostics", "line-numbers", "spacer", "diff"]
line-number = "relative"
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = false

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "error"

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "diagnostics"]
right = ["version-control", "spacer", "file-type", "file-encoding"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
