[[language]]
name = "toml"
auto-format = true


[[language]]
name = "c"
auto-format = true
file-types = ["c", "h"]
formatter = { command = "clang-format", args = [
  "--style={IndentWidth: 4, TabWidth: 4, UseTab: Never}",
] }


[[language]]
name = "python"
auto-format = true
language-servers = [{ name = "basedpyright", except-features = ["diagnostics"]}, "ruff"]

[language.formatter]
command = "black"
args = ["-", "--quiet", "--line-length=120", "--skip-string-normalization"]


[[language]]
name = "javascript"
auto-format = true


[[language]]
name = "typescript"
auto-format = true


[[language]]
name = "jsx"
auto-format = true


[[language]]
name = "tsx"
auto-format = true
