[[language]]
name = "toml"
auto-format = true
formatter = { command = "taplo", args = ["fmt", "-"] }


[[language]]
name = "c"
auto-format = true
file-types = ["c", "h"]
formatter = { command = "clang-format", args = [
  "--style={IndentWidth: 4, TabWidth: 4, UseTab: Never}",
] }

[[language]]
name = "python"
auto-format = true
formatter = { command = "ruff", args = ["format", "-"] }
language-servers = ["pyright"]


[[language]]
name = "javascript"
auto-format = true


[[language]]
name = "typescript"
auto-format = true


[[language]]
name = "jsx"
auto-format = true


[[language]]
name = "tsx"
auto-format = true
