[[language]]
name = "toml"
auto-format = true


[[language]]
name = "c"
auto-format = true
file-types = ["c", "h"]
formatter = { command = "clang-format", args = [
  "--style={IndentWidth: 4, TabWidth: 4, UseTab: Never}",
] }


[[language]]
name = "python"
auto-format = true
language-servers = ["pylsp"]

[language-server.pylsp.config.pylsp.plugins]
ruff.enabled = true
black.enabled = true
isort.enabled = true
rope_autoimport.enabled = true

[language-server.pylsp.config.pylsp.plugins.black]
args = [
  "-",
  "--quiet",
  "--line-length=120",
  "--skip-string-normalization",
]

[[language]]
name = "javascript"
auto-format = true


[[language]]
name = "typescript"
auto-format = true


[[language]]
name = "jsx"
auto-format = true


[[language]]
name = "tsx"
auto-format = true
